print("we:", "will:" , "learn!:" , '2.1' ,'"2+2"' , "2.2" , '2+2' , "2.3" , '"2" + "2"') 
print('2.1 provided we perform 2+2 with "" \n Huzzah!')
print('2.2 provided we perform 2+2 with no ""\n\n')
print('2.3 provided we perform 2+2 with both numbers enclosed with ""')
print('seemed like the modification hit space bar on its own')
